# coding: utf-8

"""
    AXIBO OPENSOURCE API

    No description provided   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@axibo.com
    
"""


import pprint
import re  # noqa: F401

import six


class ControlCMD(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'position': 'ControlCMDPosition',
        'velocity': 'ControlCMDPosition',
        'timestamp': 'ControlCMDPosition'
    }

    attribute_map = {
        'position': 'position',
        'velocity': 'velocity',
        'timestamp': 'timestamp'

    }

    def __init__(self, position=None, velocity=None,timestamp=None):  # noqa: E501
        """ControlCMD - a model defined in Swagger"""  # noqa: E501

        self._position = None
        self._velocity = None
        self._timestamp = None

        self.discriminator = None

        if position is not None:
            self.position = position
        if velocity is not None:
            self.velocity = velocity
        if timestamp is not None:
            self.timestamp = timestamp

    @property
    def position(self):
        """Gets the position of this ControlCMD.  # noqa: E501


        :return: The position of this ControlCMD.  # noqa: E501
        :rtype: ControlCMDPosition
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this ControlCMD.


        :param position: The position of this ControlCMD.  # noqa: E501
        :type: ControlCMDPosition
        """

        self._position = position

    @property
    def velocity(self):
        """Gets the velocity of this ControlCMD.  # noqa: E501


        :return: The velocity of this ControlCMD.  # noqa: E501
        :rtype: ControlCMDPosition
        """
        return self._velocity

    @velocity.setter
    def velocity(self, velocity):
        """Sets the velocity of this ControlCMD.


        :param velocity: The velocity of this ControlCMD.  # noqa: E501
        :type: ControlCMDPosition
        """

        self._velocity = velocity
    @property
    def timestamp(self):
        """Gets the timestamp of this ControlCMD.  # noqa: E501


        :return: The timestamp of this ControlCMD.  # noqa: E501
        :rtype: ControlCMDPosition
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this ControlCMD.


        :param timestamp: The timestamp of this ControlCMD.  # noqa: E501
        :type: ControlCMDPosition
        """

        self._timestamp = timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ControlCMD, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ControlCMD):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
