# coding: utf-8

"""
    AXIBO OPENSOURCE API

    No description provided   # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: contact@axibo.com
    
"""


import pprint
import re  # noqa: F401

import six


class WifiList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'saved_wifi_list': 'list[str]',
        'available_wifis': 'list[str]'
    }

    attribute_map = {
        'saved_wifi_list': 'savedWifiList',
        'available_wifis': 'availableWifis'
    }

    def __init__(self, saved_wifi_list=None, available_wifis=None):  # noqa: E501
        """WifiList - a model defined in Swagger"""  # noqa: E501

        self._saved_wifi_list = None
        self._available_wifis = None
        self.discriminator = None

        if saved_wifi_list is not None:
            self.saved_wifi_list = saved_wifi_list
        if available_wifis is not None:
            self.available_wifis = available_wifis

    @property
    def saved_wifi_list(self):
        """Gets the saved_wifi_list of this WifiList.  # noqa: E501


        :return: The saved_wifi_list of this WifiList.  # noqa: E501
        :rtype: list[str]
        """
        return self._saved_wifi_list

    @saved_wifi_list.setter
    def saved_wifi_list(self, saved_wifi_list):
        """Sets the saved_wifi_list of this WifiList.


        :param saved_wifi_list: The saved_wifi_list of this WifiList.  # noqa: E501
        :type: list[str]
        """

        self._saved_wifi_list = saved_wifi_list

    @property
    def available_wifis(self):
        """Gets the available_wifis of this WifiList.  # noqa: E501


        :return: The available_wifis of this WifiList.  # noqa: E501
        :rtype: list[str]
        """
        return self._available_wifis

    @available_wifis.setter
    def available_wifis(self, available_wifis):
        """Sets the available_wifis of this WifiList.


        :param available_wifis: The available_wifis of this WifiList.  # noqa: E501
        :type: list[str]
        """

        self._available_wifis = available_wifis

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WifiList, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WifiList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
